### ISSUE TITLE
still 

### ISSUE THREAD

**Issue by muescha** [moonmeister/gatsby-plugin-readingtime#3]
your changes in https://github.com/moonmeister/gatsby-plugin-readingtime/commit/9b2c19ec67ab206b53cd45e88169e05fe74d7ca1 not published to npm 
it results still the error:

```text
warn unable to find prism language 'jsgatsby-node.js' for highlighting. applying generic code block
```

**Comment by moonmeister** [comment]
Fixed with new release. Thanks.

**Comment by muescha** [comment]
thx :)
