### ISSUE TITLE
How to use it with prismic

### ISSUE THREAD

**Issue by ohlr** [moonmeister/gatsby-plugin-readingtime#4]
I'm using Prismic as source of content in particular [gatsby-source-prismic-graphql](https://github.com/prismicio/gatsby-source-prismic-graphql) this plugin to pull content.

The nodes created by the plugin look like this:
![image](https://user-images.githubusercontent.com/26937880/88393989-efddeb00-cdbe-11ea-9765-b380e72d488b.png)

However when using this plugin config:
```
           resolve: `gatsby-plugin-readingtime`,
            options: {
                config: {
                    // configuration for reading-time package https://github.com/ngryman/reading-time
                },
                types: {
                    // Key: GraphQL Type to add reading times to, Value: Resolver function takes source node of Defined GraphQL type and returns content to be processed.
                    prismic: (source) => {
                        console.log(source);
                        const { blocks } = source;
                        return blocks.map((block) => block.saveContent).join("");
                    },
                },
            },
```

I'm getting this error in the build log:
```
warn `createResolvers` passed resolvers for type `prismic` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers.
```

Is there something obvious that I m doing wrong?

**Comment by moonmeister** [comment]
So this is a problem with the source plugin, kinda, but mostly with [schema stitching](https://www.gatsbyjs.org/docs/third-party-graphql). `gatsby-source-prismic-graphql` uses schema stitching to do it's data fetching. The terrible part of schema stitching is that it actually bypasses Gatsby's internal data model and node system. This means it never creates data types that you can act on using Gatsby's node-apis. 

You have two options, my recommendation would be to move to `gatsby-source-prismic` which does not use schema stitching, and would allow you to then use this plugin. If this isn't possible, your only option is to use the readingtime package client side to calculate this information.

**Comment by ohlr** [comment]
Thank you for the fast and detailed information
